import bcrypt from "bcryptjs";
import type { AppConfig, User } from "./types";

const now = new Date().toISOString();

export const users: User[] = [
  {
    id: "usr-admin-001",
    name: "Admin FinTrack",
    email: "admin@fintrack.app",
    password: bcrypt.hashSync("admin123", 10),
    role: "admin",
    status: "active",
    createdAt: now,
  },
  {
    id: "usr-demo-001",
    name: "Andi Pratama",
    email: "demo@fintrack.app",
    password: bcrypt.hashSync("demo123", 10),
    role: "owner",
    status: "active",
    createdAt: now,
  },
];

export let appConfig: AppConfig = {
  appName: "FinTrack",
  tagline: "Kelola keuangan pribadimu",
  logoType: "icon",
  logoIcon: "TrendingUp",
  logoImageUrl: "",
  primaryColor: "#6366f1",
  accentColor: "#8b5cf6",
  currency: "IDR",
  dateFormat: "dd/MM/yyyy",
  faviconUrl: "",
  footerText: "© 2026 FinTrack",
};

export function setAppConfig(updates: Partial<AppConfig>) {
  appConfig = { ...appConfig, ...updates };
  return appConfig;
}

export const db = {
  wallets: [
    {
      id: "w-bca",
      name: "BCA",
      type: "bank",
      balance: 15000000,
      currency: "IDR",
      color: "#1e40af",
      icon: "🏦",
      children: [
        {
          id: "w-bca-jajan",
          name: "Kantong Jajan",
          type: "bank",
          balance: 500000,
          currency: "IDR",
          color: "#3b82f6",
          icon: "🍔",
          parentId: "w-bca",
        },
        {
          id: "w-bca-tabungan",
          name: "Kantong Tabungan",
          type: "savings",
          balance: 3000000,
          currency: "IDR",
          color: "#0ea5e9",
          icon: "💰",
          parentId: "w-bca",
        },
      ],
    },
    {
      id: "w-mandiri",
      name: "Mandiri",
      type: "bank",
      balance: 8000000,
      currency: "IDR",
      color: "#d97706",
      icon: "🏛️",
    },
    {
      id: "w-gopay",
      name: "GoPay",
      type: "e-wallet",
      balance: 250000,
      currency: "IDR",
      color: "#22c55e",
      icon: "📱",
    },
    {
      id: "w-cash",
      name: "Cash",
      type: "cash",
      balance: 500000,
      currency: "IDR",
      color: "#64748b",
      icon: "💵",
    },
  ],
  transactions: [
    {
      id: "tx-1",
      type: "expense",
      amount: 25000,
      category: "Kopi",
      categoryIcon: "☕",
      walletId: "w-bca-jajan",
      walletName: "Kantong Jajan",
      description: "Beli kopi",
      date: new Date().toISOString(),
    },
    {
      id: "tx-2",
      type: "income",
      amount: 8000000,
      category: "Gaji",
      categoryIcon: "💼",
      walletId: "w-bca",
      walletName: "BCA",
      description: "Gaji bulanan",
      date: new Date().toISOString(),
    },
  ],
  budgets: [
    {
      id: "bdg-1",
      category: "Makan",
      categoryIcon: "🍔",
      limit: 1500000,
      spent: 820000,
      period: "monthly",
      color: "#f97316",
    },
    {
      id: "bdg-2",
      category: "Transport",
      categoryIcon: "🚗",
      limit: 700000,
      spent: 520000,
      period: "monthly",
      color: "#3b82f6",
    },
  ],
  bills: [
    {
      id: "bill-1",
      name: "Internet Rumah",
      amount: 350000,
      dueDate: new Date(Date.now() + 86400000 * 5).toISOString(),
      status: "unpaid",
      category: "Utilitas",
      icon: "🌐",
      isRecurring: true,
      recurringPeriod: "monthly",
    },
  ],
  savingGoals: [
    {
      id: "goal-1",
      name: "Dana Darurat",
      icon: "🛡️",
      targetAmount: 30000000,
      currentAmount: 8500000,
      deadline: new Date(Date.now() + 86400000 * 180).toISOString(),
      color: "#22c55e",
    },
  ],
  notes: [
    {
      id: "note-1",
      title: "Ide hemat bulan ini",
      content: "Kurangi beli kopi di luar, masak dari rumah.",
      tags: ["hemat"],
      createdAt: now,
      updatedAt: now,
      color: "#1a1d27",
    },
  ],
  recurringTransactions: [
    {
      id: "rec-1",
      name: "Netflix",
      amount: 65000,
      type: "expense",
      category: "Hiburan",
      categoryIcon: "🎬",
      walletId: "w-bca",
      period: "monthly",
      nextDate: new Date(Date.now() + 86400000 * 10).toISOString(),
      isActive: true,
    },
  ],
  investments: [],
  debts: [],
  cards: [],
  wishlist: [],
  reimbursements: [],
  teamMembers: [],
  splitBills: [],
  categories: [
    {
      id: "cat-inc-gaji",
      type: "income",
      name: "Gaji",
      icon: "💼",
      color: "#22c55e",
      sortOrder: 0,
      isSystem: true,
      subCategories: [
        {
          id: "sub-inc-gaji-pokok",
          name: "Gaji Pokok",
          icon: "💵",
          color: "#22c55e",
          sortOrder: 0,
          isSystem: true,
          categoryId: "cat-inc-gaji",
          createdAt: now,
          updatedAt: now,
        },
        {
          id: "sub-inc-gaji-bonus",
          name: "Bonus",
          icon: "🎁",
          color: "#16a34a",
          sortOrder: 1,
          isSystem: true,
          categoryId: "cat-inc-gaji",
          createdAt: now,
          updatedAt: now,
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cat-inc-freelance",
      type: "income",
      name: "Freelance",
      icon: "💻",
      color: "#06b6d4",
      sortOrder: 1,
      isSystem: true,
      subCategories: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cat-inc-investasi",
      type: "income",
      name: "Investasi",
      icon: "📈",
      color: "#a855f7",
      sortOrder: 2,
      isSystem: true,
      subCategories: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cat-inc-hadiah",
      type: "income",
      name: "Hadiah",
      icon: "🎁",
      color: "#f59e0b",
      sortOrder: 3,
      isSystem: true,
      subCategories: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cat-exp-makan",
      type: "expense",
      name: "Makan",
      icon: "🍔",
      color: "#f97316",
      sortOrder: 0,
      isSystem: true,
      subCategories: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cat-exp-transport",
      type: "expense",
      name: "Transport",
      icon: "🚗",
      color: "#3b82f6",
      sortOrder: 1,
      isSystem: true,
      subCategories: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cat-exp-belanja",
      type: "expense",
      name: "Belanja",
      icon: "🛍️",
      color: "#a855f7",
      sortOrder: 2,
      isSystem: true,
      subCategories: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cat-exp-hiburan",
      type: "expense",
      name: "Hiburan",
      icon: "🎬",
      color: "#ec4899",
      sortOrder: 3,
      isSystem: true,
      subCategories: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cat-exp-kesehatan",
      type: "expense",
      name: "Kesehatan",
      icon: "🏥",
      color: "#22c55e",
      sortOrder: 4,
      isSystem: true,
      subCategories: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "cat-exp-tagihan",
      type: "expense",
      name: "Tagihan",
      icon: "💡",
      color: "#6366f1",
      sortOrder: 5,
      isSystem: true,
      subCategories: [],
      createdAt: now,
      updatedAt: now,
    },
  ],
  subCategories: [],
};
